Repository randersonLemos/mc426, pull requests merged in 2023-06, with the labels that each got.

#35 Feature adição de descrição de arquitetura2
  README.md
Labels: AvaliacaoA4.1

#37 Atualizar README.md da main
  README.md
Labels: documentation

#38 Implementacao do padrão de projeto ADAPTER
  frontend/components/adminSignIn/adminSignIn.tsx
  frontend/components/adminSignUp/adminSignUp.tsx
  frontend/components/signUpForm/signUpForm.tsx
  frontend/helpers/adpter/backendAdapter.ts
  frontend/helpers/adpter/backendFirebase.ts
  frontend/helpers/customWindow.ts
  frontend/pages/admin/dashboard/index.tsx
Labels: AvaliacaoA4.1

#40 Tratamento com refatoração do code smell Dispensables
  frontend/components/adminSignIn/adminSignIn.tsx
  frontend/components/sendMessageForm/sendMessageForm.tsx
  frontend/components/sendMessageForm/sendMessageFormValidation.cy.tsx
  frontend/components/signUpForm/signUpForm.tsx
Labels: AvaliacaoA4.2

#43 42 implementação de testes
  frontend/components/adminSignIn/adminSignIn.tsx
  frontend/components/adminSignUp/adminSignUp.tsx
  frontend/components/adminSignUp/adminSignUpRenders.cy.tsx
  frontend/components/sendMessageForm/sendMessageForm.tsx
  frontend/components/sendMessageForm/sendMessageFormSendMessageForm.cy.tsx
  frontend/components/sendMessageForm/sendMessageFormValidation.cy.tsx
  frontend/components/signUpForm/signUpForm.tsx
  frontend/components/signUpForm/signUpFormValidation.cy.tsx
  frontend/cypress/tests/adminDashboard/indexAdmin.cy.tsx
  frontend/cypress/tests/adminSignIn/invalidEmail.cy.tsx
  frontend/cypress/tests/adminSignIn/passwordLowerBound.cy.tsx
  frontend/cypress/tests/adminSignIn/passwordNumber.cy.tsx
  frontend/cypress/tests/adminSignIn/passwordSpecialChar.cy.tsx
  frontend/cypress/tests/adminSignIn/passwordUpperBound.cy.tsx
  frontend/cypress/tests/adminSignIn/passwordUppercase.cy.tsx
  frontend/cypress/tests/adminSignIn/validEmail.cy.tsx
  frontend/cypress/tests/adminSignIn/validPassword.cy.tsx
  frontend/cypress/tests/adminSignUp/invalidConfirmPassword.cy.tsx
  frontend/cypress/tests/adminSignUp/invalidEmail.cy.tsx
  frontend/cypress/tests/adminSignUp/nameLowerBound.cy.tsx
  frontend/cypress/tests/adminSignUp/nameUpperBound.cy.tsx
  frontend/cypress/tests/adminSignUp/passwordLowerBound.cy.tsx
  frontend/cypress/tests/adminSignUp/passwordNumber.cy.tsx
  frontend/cypress/tests/adminSignUp/passwordSpecialChar.cy.tsx
  frontend/cypress/tests/adminSignUp/passwordUpperBound.cy.tsx
  frontend/cypress/tests/adminSignUp/passwordUppercase.cy.tsx
  frontend/cypress/tests/adminSignUp/validEmail.cy.tsx
  frontend/cypress/tests/adminSignUp/validName.cy.tsx
  frontend/cypress/tests/adminSignUp/validPassword.cy.tsx
  frontend/cypress/tests/sendMessageForm/emptyMessage.cy.tsx
  frontend/cypress/tests/sendMessageForm/emptyRecipients.cy.tsx
  frontend/cypress/tests/sendMessageForm/shouldSendMessage.cy.tsx
  frontend/cypress/tests/signUpForm/cityLowerBound.cy.tsx
  frontend/cypress/tests/signUpForm/cityUpperBound.cy.tsx
  frontend/cypress/tests/signUpForm/invalidBirthday.cy.tsx
  frontend/cypress/tests/signUpForm/invalidEmail.cy.tsx
  frontend/cypress/tests/signUpForm/invalidPhone.cy.tsx
  frontend/cypress/tests/signUpForm/nameLowerBound.cy.tsx
  frontend/cypress/tests/signUpForm/nameUpperBound.cy.tsx
  frontend/cypress/tests/signUpForm/validBirthday.cy.tsx
  frontend/cypress/tests/signUpForm/validCity.cy.tsx
  frontend/cypress/tests/signUpForm/validEmail.cy.tsx
  frontend/cypress/tests/signUpForm/validName.cy.tsx
  frontend/cypress/tests/signUpForm/validPhone.cy.tsx
Labels: AvaliacaoA5
